"""One-time script to patch restaurants.json with enriched data."""
import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent
DATA_FILE = ROOT / "data" / "restaurants.json"

# Enrichment patches keyed by restaurant id.
# Only include fields that should overwrite the base data.
PATCHES = {
  "semma-greenwich-village": {
    "address": "60 Greenwich Avenue, New York, NY 10011",
    "lat": 40.7360, "lng": -74.0005,
    "website": "https://semma.nyc",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Chef Vijay Kumar's personal tribute to Tamil Nadu's cuisine — fiery, coconut-rich Southern Indian cooking that transformed how New York thinks about Indian food.",
    "popular_dishes": ["Dosa", "Gunpowder Idli", "Chettinad Chicken Curry", "Rasam"],
    "price_per_item": "$18-42",
  },
  "atomix-nomad": {
    "address": "104 East 30th Street, New York, NY 10016",
    "lat": 40.7440, "lng": -73.9838,
    "website": "https://atomixnyc.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Tock",
    "description": "Junghyun and Ellia Park's subterranean Korean tasting menu, where each course arrives with a handwritten card and punchy, modern technique.",
    "popular_dishes": ["Seasonal 10-course tasting menu"],
    "price_per_item": "$225 per person",
  },
  "le-bernardin-midtown": {
    "address": "155 West 51st Street, New York, NY 10019",
    "lat": 40.7614, "lng": -73.9817,
    "website": "https://le-bernardin.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Eric Ripert's four-star seafood institution where pristine fish and precise French technique have earned an unbroken run at the top of New York dining for 30 years.",
    "popular_dishes": ["Barely Cooked Salmon", "Pounded Tuna with Foie Gras", "Langoustine", "Fluke in Apple-Dill Broth"],
    "price_per_item": "$185+ prix fixe",
  },
  "kabawa-east-village": {
    "address": "8 Extra Place, New York, NY 10003",
    "lat": 40.7265, "lng": -73.9906,
    "website": "https://www.instagram.com/kabawa",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": None,
    "description": "Paul Carmichael's joyful Caribbean kitchen in the former Momofuku Ko space, serving a three-course prix fixe of vibrant Barbadian-rooted dishes with tie-dyed warmth.",
    "popular_dishes": ["Roti with Tamarind Eggplant", "Braised Goat with Curry Leaves", "Cream Cheese Flan"],
    "price_per_item": "$95 prix fixe",
  },
  "has-snack-bar-lower-east-side": {
    "address": "297 Broome Street, New York, NY 10002",
    "lat": 40.7185, "lng": -73.9989,
    "website": "https://www.instagram.com/has_dac_biet",
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "Anthony Ha and Sadie Mae Burns-Ha's permanent home for their celebrated pop-up, blending Vietnamese and French flavors with seasonal precision and a great natural wine list.",
    "popular_dishes": ["Seasonal French-Vietnamese small plates", "Banh Mi", "Natural wines"],
    "price_per_item": "$25-45",
  },
  "king-south-village": {
    "address": "18 King Street, New York, NY 10014",
    "lat": 40.7264, "lng": -74.0042,
    "website": "https://www.king-restaurant.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Clare de Boer's intimate South Village room celebrated for rustic, vegetable-forward Mediterranean cooking with whole-roasted meats and impeccable sourcing.",
    "popular_dishes": ["Whole Roasted Chicken", "Pasta", "Seasonal Grain Dishes", "Tarte Tatin"],
    "price_per_item": "$28-48",
  },
  "penny-east-village": {
    "address": "East Village, New York, NY",
    "lat": 40.7264, "lng": -73.9844,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new East Village spot marrying French technique with pristine seafood in a relaxed setting.",
    "popular_dishes": [],
    "price_per_item": "$30-55",
  },
  "sushi-sho-midtown": {
    "address": "22 West 32nd Street, New York, NY 10001",
    "lat": 40.7487, "lng": -73.9888,
    "website": "https://sushisho.nyc",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": None,
    "description": "A reverent omakase counter from a Tokyo master, where each bite-sized piece of sushi is seasoned and served at the precise moment of perfection.",
    "popular_dishes": ["Seasonal omakase — chef's selection only"],
    "price_per_item": "$350+ omakase",
  },
  "szechuan-mountain-house-east-village": {
    "address": "23 St. Marks Place, New York, NY 10003",
    "lat": 40.7292, "lng": -73.9886,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "The East Village's most electrifying Szechuan table — numbing peppercorns, chili oil, and bold umami in a casual, welcoming room.",
    "popular_dishes": ["Dan Dan Noodles", "Mapo Tofu", "Water-Boiled Fish", "Twice-Cooked Pork"],
    "price_per_item": "$14-28",
  },
  "tatiana-upper-west-side": {
    "address": "10 Lincoln Center Plaza, New York, NY 10023",
    "lat": 40.7726, "lng": -73.9836,
    "website": "https://tatianabyko.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Kwame Onwuachi's love letter to the African diaspora — jerk chicken, goat roti, and Creole flavors served at Lincoln Center with serious style.",
    "popular_dishes": ["Jerk Chicken", "Goat Roti", "Crab Rice", "Nigerian Corn"],
    "price_per_item": "$28-48",
  },
  "188-bakery-cuchifritos-fordham-heights": {
    "address": "188 East Fordham Road, Bronx, NY 10458",
    "lat": 40.8616, "lng": -73.8963,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A beloved Bronx counter known for its cuchifritos — fried pork specialties and Puerto Rican pastries that are the real deal.",
    "popular_dishes": ["Alcapurrias", "Pasteles", "Cuchifritos", "Bacalaitos"],
    "price_per_item": "$3-12",
  },
  "aaa-bake-and-doubles-bedford-stuyvesant": {
    "address": "481 Nostrand Avenue, Brooklyn, NY 11216",
    "lat": 40.6807, "lng": -73.9503,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Brooklyn's best doubles — the beloved Trinidadian street food sandwich of fried bara bread with curried chickpeas, tamarind, and pepper sauce.",
    "popular_dishes": ["Doubles", "Aloo Pie", "Bake and Saltfish"],
    "price_per_item": "$3-10",
  },
  "abuqir-seafood-astoria": {
    "address": "25-22 Steinway Street, Astoria, NY 11103",
    "lat": 40.7694, "lng": -73.9088,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "An Egyptian seafood institution in Astoria where whole fish is fried or grilled to order and the atmosphere is pure neighborhood warmth.",
    "popular_dishes": ["Whole Fried Fish", "Calamari", "Shrimp Saganaki", "Hummus"],
    "price_per_item": "$18-35",
  },
  "aska-williamsburg": {
    "address": "47 South 5th Street, Brooklyn, NY 11249",
    "lat": 40.7133, "lng": -73.9642,
    "website": "https://www.askanyc.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Fredrik Berselius's Scandinavian tasting menu in Williamsburg — moody, foraged, and ethereally precise, channeling the Nordic wilderness through Brooklyn.",
    "popular_dishes": ["Seasonal Nordic tasting menu", "Fermented dishes", "Pine and forest flavors"],
    "price_per_item": "$195+ per person",
  },
  "atoboy-nomad": {
    "address": "43 East 28th Street, New York, NY 10016",
    "lat": 40.7443, "lng": -73.9839,
    "website": "https://www.atoboynyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "The more accessible sibling of Atomix — choose-your-own Korean banchan-style sharing plates in a warm, approachable setting.",
    "popular_dishes": ["Seasonal Korean banchan", "Pork Belly", "Seafood Pancake", "Bibimbap"],
    "price_per_item": "$75-95 prix fixe",
  },
  "barbuto-meatpacking-district": {
    "address": "113 Jane Street, New York, NY 10014",
    "lat": 40.7382, "lng": -74.0077,
    "website": "https://barbutonyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Jonathan Waxman's Italian-inflected New American landmark, famous for its roast chicken and the breezy garage-door dining room.",
    "popular_dishes": ["JW Roast Chicken", "Kale Salad", "Pasta", "Whole Roasted Fish"],
    "price_per_item": "$28-52",
  },
  "barney-greengrass-upper-west-side": {
    "address": "541 Amsterdam Avenue, New York, NY 10024",
    "lat": 40.7854, "lng": -73.9773,
    "website": "https://barneygreengrass.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "The century-old 'Sturgeon King' of the Upper West Side — the city's gold standard for smoked fish, cream cheese, and an unimprovable bagel.",
    "popular_dishes": ["Nova Lox", "Sturgeon", "Whitefish Salad", "Eggs and Salmon"],
    "price_per_item": "$18-35",
  },
  "birria-landia-jackson-heights": {
    "address": "76-05 Roosevelt Avenue, Jackson Heights, NY 11372",
    "lat": 40.7462, "lng": -73.8895,
    "website": "https://birrialandia.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "The Queens truck-turned-storefront that put birria tacos on the map — deeply spiced consommé, tender beef, and perfectly crispy-dipped tortillas.",
    "popular_dishes": ["Birria Tacos", "Consomme", "Quesabirria", "Mulitas"],
    "price_per_item": "$5-18",
  },
  "borgo-midtown": {
    "address": "Midtown, New York, NY",
    "lat": 40.7549, "lng": -73.9840,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new Midtown Italian spot earning praise for its regional Italian cooking and well-edited wine list.",
    "popular_dishes": [],
    "price_per_item": "$28-52",
  },
  "bridges-chinatown": {
    "address": "Chinatown, New York, NY 10013",
    "lat": 40.7157, "lng": -73.9970,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new American-French kitchen in Chinatown drawing on the neighborhood's energy for an inventive, produce-driven menu.",
    "popular_dishes": [],
    "price_per_item": "$28-48",
  },
  "bungalow-east-village": {
    "address": "East Village, New York, NY 10009",
    "lat": 40.7264, "lng": -73.9844,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new East Village Indian restaurant bringing regional Indian cooking with modern sensibility to a neighborhood already rich with South Asian food.",
    "popular_dishes": [],
    "price_per_item": "$22-45",
  },
  "cafe-kestrel-red-hook": {
    "address": "Red Hook, Brooklyn, NY 11231",
    "lat": 40.6745, "lng": -74.0062,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A destination Red Hook restaurant with a European-leaning menu that rewards the trip from Manhattan.",
    "popular_dishes": [],
    "price_per_item": "$28-52",
  },
  "cafe-mado-prospect-heights": {
    "address": "Prospect Heights, Brooklyn, NY 11238",
    "lat": 40.6757, "lng": -73.9601,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A neighborhood gem in Prospect Heights serving thoughtful New American food with French inflections in a warm, intimate setting.",
    "popular_dishes": [],
    "price_per_item": "$25-45",
  },
  "carnitas-ramirez-east-village": {
    "address": "115 1st Avenue, New York, NY 10003",
    "lat": 40.7261, "lng": -73.9844,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A tiny East Village counter devoted to carnitas — slow-cooked pork done right, served in tacos and tortas at very reasonable prices.",
    "popular_dishes": ["Carnitas Tacos", "Carnitas Torta", "Salsa Verde"],
    "price_per_item": "$5-15",
  },
  "casa-mono-union-square": {
    "address": "52 Irving Place, New York, NY 10003",
    "lat": 40.7360, "lng": -73.9868,
    "website": "https://casamononyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Mario Batali's Spanish tapas bar (now under new leadership) near Gramercy Park — one of NYC's best spots for Iberian small plates and jamón.",
    "popular_dishes": ["Jamon Iberico", "Bone Marrow", "Croquetas", "Tortilla Espanola"],
    "price_per_item": "$18-38",
  },
  "cervos-lower-east-side": {
    "address": "43 Canal Street, New York, NY 10002",
    "lat": 40.7166, "lng": -73.9990,
    "website": "https://cervosnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A sun-drenched Portuguese and Spanish wine bar on Canal Street, beloved for its tinned fish, fresh seafood, and natural wine selection.",
    "popular_dishes": ["Tinned Fish", "Gambas", "Grilled Octopus", "Fried Bacalhau"],
    "price_per_item": "$18-38",
  },
  "chambers-tribeca": {
    "address": "TriBeCa, New York, NY 10013",
    "lat": 40.7195, "lng": -74.0089,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A smart TriBeCa American restaurant earning attention for its precise, ingredient-driven cooking.",
    "popular_dishes": [],
    "price_per_item": "$28-52",
  },
  "chez-ma-tante-greenpoint": {
    "address": "90 Calyer Street, Brooklyn, NY 11222",
    "lat": 40.7240, "lng": -73.9509,
    "website": "https://chezmatantebk.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A beloved Greenpoint neighborhood restaurant with a European-leaning menu, famous for its Dutch baby pancake brunch and relaxed dinner service.",
    "popular_dishes": ["Dutch Baby Pancake", "Roast Chicken", "Pasta", "Seasonal Vegetables"],
    "price_per_item": "$22-42",
  },
  "cho-dang-gol-midtown": {
    "address": "55 West 35th Street, New York, NY 10001",
    "lat": 40.7507, "lng": -73.9882,
    "website": "https://chodanggol.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Koreatown institution specializing in house-made tofu — soft, silken, and used in every form across a menu of classic Korean comfort food.",
    "popular_dishes": ["Sundubu Jjigae", "Dubu Jorim", "Doenjang Jjigae", "Bibimbap"],
    "price_per_item": "$16-28",
  },
  "chongqing-lao-zao-flushing": {
    "address": "Flushing, Queens, NY 11355",
    "lat": 40.7580, "lng": -73.8303,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Flushing's most exciting Chongqing restaurant, bringing the fiery, numbing street food of Sichuan's mountain city to Queens.",
    "popular_dishes": ["Chongqing Noodles", "Spicy Hotpot", "Beef Offal Soup", "Steamed Buns"],
    "price_per_item": "$12-25",
  },
  "cka-ka-qellu-belmont": {
    "address": "2417 Arthur Avenue, Bronx, NY 10458",
    "lat": 40.8518, "lng": -73.8878,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "The Bronx's Arthur Avenue gets a taste of the Balkans at this Albanian restaurant serving hearty, meat-forward dishes in a welcoming family environment.",
    "popular_dishes": ["Tavë Kosi", "Grilled Meats", "Burek", "Albanian Salad"],
    "price_per_item": "$18-35",
  },
  "claud-east-village": {
    "address": "120 East 7th Street, New York, NY 10009",
    "lat": 40.7265, "lng": -73.9835,
    "website": "https://claudnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A French-inflected East Village newcomer with a wine-bar sensibility — the kind of effortless cooking that makes everything look easy.",
    "popular_dishes": ["Seasonal small plates", "Natural wine"],
    "price_per_item": "$22-42",
  },
  "cocina-consuelo-harlem": {
    "address": "Harlem, New York, NY 10027",
    "lat": 40.8116, "lng": -73.9527,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Harlem Mexican kitchen serving the homestyle cooking of Oaxaca and Puebla with heart and generosity.",
    "popular_dishes": ["Mole", "Tamales", "Enchiladas", "Agua Frescas"],
    "price_per_item": "$14-28",
  },
  "court-street-grocers-carroll-gardens": {
    "address": "485 Court Street, Brooklyn, NY 11231",
    "lat": 40.6779, "lng": -73.9948,
    "website": "https://courtstreetgrocers.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Brooklyn's most beloved sandwich shop — a grocery and deli combining exceptional ingredients with thoughtful, creative sandwich-making.",
    "popular_dishes": ["Roast Pork Sandwich", "Turkey Melt", "Hot Coppa", "Seasonal specials"],
    "price_per_item": "$14-22",
  },
  "crown-shy-financial-district": {
    "address": "70 Pine Street, New York, NY 10005",
    "lat": 40.7066, "lng": -74.0079,
    "website": "https://crownshy.nyc",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "James Kent's sophisticated Financial District restaurant in a landmark Art Deco tower, with ambitious American cooking and a serious bar program.",
    "popular_dishes": ["Oyster Mushroom", "Duck", "Seasonal Pasta", "Cheese selections"],
    "price_per_item": "$32-58",
  },
  "daniel-upper-east-side": {
    "address": "60 East 65th Street, New York, NY 10065",
    "lat": 40.7651, "lng": -73.9694,
    "website": "https://danielnyc.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Daniel Boulud's crown jewel — a palatial Upper East Side French restaurant where classical technique and seasonal luxury define one of the city's great fine dining experiences.",
    "popular_dishes": ["Tournedos Rossini", "Black Sea Bass", "Foie Gras", "Seasonal Tasting Menu"],
    "price_per_item": "$145+ prix fixe",
  },
  "dera-jackson-heights": {
    "address": "37-47 74th Street, Jackson Heights, NY 11372",
    "lat": 40.7476, "lng": -73.8905,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Jackson Heights restaurant serving the authentic subcontinental cooking of Pakistan, Bangladesh, Nepal and India to a diverse neighborhood clientele.",
    "popular_dishes": ["Nihari", "Biryani", "Haleem", "Karahi"],
    "price_per_item": "$12-25",
  },
  "dhamaka-lower-east-side": {
    "address": "119 Delancey Street, New York, NY 10002",
    "lat": 40.7189, "lng": -73.9880,
    "website": "https://dhamakanyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Chintan Pandya's temple to the rustic cooking of rural India — offal curries, whole roasted lamb, and the kind of bold flavors rarely seen in NYC.",
    "popular_dishes": ["Whole Roasted Lamb Shoulder", "Goat Brain Curry", "Mushroom Khichdi", "Lasuni Gobi"],
    "price_per_item": "$24-65",
  },
  "don-peppe-south-ozone-park": {
    "address": "135-58 Lefferts Boulevard, South Ozone Park, NY 11420",
    "lat": 40.6697, "lng": -73.8243,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A no-frills Queens Italian-American institution in business for over 50 years — cash only, no menu, and whatever they feel like cooking that day.",
    "popular_dishes": ["Veal Parmigiana", "Sunday Gravy", "Braciole", "Clams Casino"],
    "price_per_item": "$25-45",
  },
  "ewes-delicious-treats-new-lots": {
    "address": "New Lots, Brooklyn, NY 11208",
    "lat": 40.6614, "lng": -73.8858,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Nigerian-owned Brooklyn bakery and snack shop serving West African sweets, savories, and a taste of home for the local community.",
    "popular_dishes": ["Chin Chin", "Puff Puff", "Meat Pie", "Jollof Rice"],
    "price_per_item": "$4-15",
  },
  "eyval-bushwick": {
    "address": "Bushwick, Brooklyn, NY 11237",
    "lat": 40.7044, "lng": -73.9239,
    "website": "https://eyvalnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "An Iranian restaurant in Bushwick bringing the aromatic, herb-rich cooking of Persia to New York with warmth and contemporary sensibility.",
    "popular_dishes": ["Kabob", "Ghormeh Sabzi", "Ash Reshteh", "Saffron Rice"],
    "price_per_item": "$22-42",
  },
  "the-four-horsemen-williamsburg": {
    "address": "295 Grand Street, Brooklyn, NY 11211",
    "lat": 40.7131, "lng": -73.9593,
    "website": "https://fourhorsemenbk.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "James Murphy's (of LCD Soundsystem) celebrated natural wine bar in Williamsburg, pairing an exceptional bottle list with smart, ingredient-driven small plates.",
    "popular_dishes": ["Burrata", "Pasta", "Roast Chicken", "Seasonal charcuterie"],
    "price_per_item": "$22-42",
  },
  "four-twenty-five-midtown": {
    "address": "425 Park Avenue, New York, NY 10022",
    "lat": 40.7585, "lng": -73.9720,
    "website": "https://fourtwentyfive.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Le Bernardin's Eric Ripert opens a second Midtown chapter — a polished American restaurant in a stunning Norman Foster tower on Park Avenue.",
    "popular_dishes": ["Seasonal American tasting menu", "Seafood preparations", "Wagyu beef"],
    "price_per_item": "$65-125",
  },
  "frenchette-tribeca": {
    "address": "241 West Broadway, New York, NY 10013",
    "lat": 40.7218, "lng": -74.0073,
    "website": "https://frenchettenyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Riad Nasr and Lee Hanson's influential TriBeCa bistro — a modern Paris brasserie that helped launch NYC's natural wine and casual French fine-dining moment.",
    "popular_dishes": ["Steak Frites", "Duck a l'Orange", "Sole Meunière", "Vin Jaune Chicken"],
    "price_per_item": "$28-52",
  },
  "gage-and-tollner-downtown-brooklyn": {
    "address": "372 Fulton Street, Brooklyn, NY 11201",
    "lat": 40.6928, "lng": -73.9866,
    "website": "https://gageandtollner.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A stunning Victorian restaurant resurrected in Downtown Brooklyn, serving refined American seafood in the city's most beautiful dining room.",
    "popular_dishes": ["Lobster Newberg", "Clam Bellies", "Iceberg Wedge", "Oysters"],
    "price_per_item": "$28-58",
  },
  "golden-diner-chinatown": {
    "address": "123 Madison Street, New York, NY 10002",
    "lat": 40.7134, "lng": -73.9940,
    "website": "https://goldendiner.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Sam Yoo's celebrated Chinatown diner blending classic American diner comfort with East Asian flavors — the egg sandwich is legendary.",
    "popular_dishes": ["Soy Glazed Bacon Egg Sandwich", "Scallion Pancake", "Bibim Chicken", "Soft Serve"],
    "price_per_item": "$14-24",
  },
  "gramercy-tavern-gramercy": {
    "address": "42 East 20th Street, New York, NY 10003",
    "lat": 40.7386, "lng": -73.9888,
    "website": "https://gramercytavern.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Danny Meyer's flagship and one of New York's most beloved restaurants — consistently excellent New American cooking in a warm, flowers-and-wood room.",
    "popular_dishes": ["Duck", "Whole Roasted Mushroom", "Tasting Menu", "Tavern menu at the bar"],
    "price_per_item": "$48-95",
  },
  "great-ny-noodletown-chinatown": {
    "address": "28 Bowery, New York, NY 10013",
    "lat": 40.7147, "lng": -73.9980,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Chinatown institution open until 4am, renowned for its roast meats, soft-shell crab in season, and no-frills Hong Kong-style noodles.",
    "popular_dishes": ["Roast Duck over Rice", "Soft-Shell Crab", "Salt-Baked Seafood", "Wonton Soup"],
    "price_per_item": "$12-25",
  },
  "the-grill-midtown-east": {
    "address": "99 East 52nd Street, New York, NY 10022",
    "lat": 40.7567, "lng": -73.9722,
    "website": "https://thegrillnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "The restored Four Seasons space reimagined as a power-lunch institution with tableside preparations, perfectly aged steaks, and 1960s Mad Men glamour.",
    "popular_dishes": ["Dover Sole Meunière", "Prime Rib", "Seafood Tower", "Caesar Salad tableside"],
    "price_per_item": "$55-120",
  },
  "hainan-chicken-house-sunset-park": {
    "address": "6322 8th Avenue, Brooklyn, NY 11220",
    "lat": 40.6484, "lng": -74.0116,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Sunset Park spot devoted to Hainanese chicken rice — silky poached chicken, fragrant rice cooked in chicken fat, and three essential dipping sauces.",
    "popular_dishes": ["Hainanese Chicken Rice", "Roast Chicken", "Chicken Congee", "Pandan Cake"],
    "price_per_item": "$12-22",
  },
  "hamburger-america-soho": {
    "address": "SoHo, New York, NY 10012",
    "lat": 40.7248, "lng": -74.0019,
    "website": "https://hamburgeramerica.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "George Motz's burger shrine opened as a brick-and-mortar after decades as a documentary and pop-up — regional American burgers done with obsessive fidelity.",
    "popular_dishes": ["Oklahoma Onion Smash Burger", "Wisconsin Butter Burger", "The Classic"],
    "price_per_item": "$10-18",
  },
  "hellbender-ridgewood": {
    "address": "Ridgewood, Queens, NY 11385",
    "lat": 40.7062, "lng": -73.9091,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Ridgewood Mexican spot earning serious attention for its nuanced, regional Mexican cooking far from the standard taco shop playbook.",
    "popular_dishes": ["Mole Negro", "Tlayuda", "Mezcal cocktails"],
    "price_per_item": "$18-35",
  },
  "ho-foods-east-village": {
    "address": "110 East 7th Street, New York, NY 10009",
    "lat": 40.7265, "lng": -73.9838,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A tiny East Village noodle shop serving Taiwanese beef noodle soup with a deeply spiced, slow-cooked broth that's become one of the city's cult bowls.",
    "popular_dishes": ["Beef Noodle Soup", "Braised Pork Rice", "Scallion Pancake", "Cold Sesame Noodles"],
    "price_per_item": "$14-22",
  },
  "houseman-hudson-square": {
    "address": "508 Greenwich Street, New York, NY 10013",
    "lat": 40.7264, "lng": -74.0079,
    "website": "https://housemanrestaurant.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Ned Baldwin's cozy Hudson Square restaurant that emphasizes offal, whole-animal cooking, and the pleasures of unfashionable cuts done brilliantly.",
    "popular_dishes": ["Beef Tartare", "Deviled Kidneys", "Rotisserie Chicken", "Seasonal vegetables"],
    "price_per_item": "$26-52",
  },
  "jean-georges-upper-west-side": {
    "address": "1 Central Park West, New York, NY 10023",
    "lat": 40.7685, "lng": -73.9819,
    "website": "https://jean-georges.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Jean-Georges Vongerichten's flagship in the Trump International Hotel — one of NYC's last great four-star French restaurants, with iconic dishes spanning 30+ years.",
    "popular_dishes": ["Egg Caviar", "Tuna Ribbons", "Spiced Crème Brûlée", "Seasonal tasting menu"],
    "price_per_item": "$145+ prix fixe",
  },
  "jeju-noodle-bar-west-village": {
    "address": "679 Greenwich Street, New York, NY 10014",
    "lat": 40.7337, "lng": -74.0077,
    "website": "https://jejunoodlebar.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A West Village spot devoted to ramyun and Korean noodles with thoughtful depth — the pork broth is rich and meticulously made.",
    "popular_dishes": ["Jeju Ramyun", "Pork Belly", "Braised Short Rib", "Tteokbokki"],
    "price_per_item": "$18-32",
  },
  "jungsik-tribeca": {
    "address": "2 Harrison Street, New York, NY 10013",
    "lat": 40.7193, "lng": -74.0089,
    "website": "https://jungsik.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Jungsik Yim's TriBeCa Korean fine dining — seasonal ingredients and French technique applied to Korean flavor principles at the highest level.",
    "popular_dishes": ["Seasonal tasting menu", "Kimchi Consommé", "Wagyu with Doenjang"],
    "price_per_item": "$225+ per person",
  },
  "keens-midtown": {
    "address": "72 West 36th Street, New York, NY 10018",
    "lat": 40.7511, "lng": -73.9876,
    "website": "https://keens.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Manhattan institution since 1885 — the legendary mutton chop and clay pipes hanging from the ceiling make Keens one of the most atmospheric rooms in the city.",
    "popular_dishes": ["Prime Rib", "Mutton Chop", "Filet Mignon", "Scotch selection"],
    "price_per_item": "$58-120",
  },
  "kisa-lower-east-side": {
    "address": "Lower East Side, New York, NY 10002",
    "lat": 40.7189, "lng": -73.9854,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Korean restaurant on the Lower East Side praised for its precise, well-sourced Korean cooking that earns comparison to the best in Koreatown.",
    "popular_dishes": ["Korean fried chicken", "Japchae", "Spicy pork"],
    "price_per_item": "$22-42",
  },
  "koloman-nomad": {
    "address": "16 West 29th Street, New York, NY 10001",
    "lat": 40.7450, "lng": -73.9872,
    "website": "https://kolomannyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Viennese cafe and restaurant in the Ace Hotel bringing the elegance of Central European coffee culture and cuisine to NoMad.",
    "popular_dishes": ["Wiener Schnitzel", "Tafelspitz", "Sachertorte", "Gulasch"],
    "price_per_item": "$28-55",
  },
  "kono-chinatown": {
    "address": "Chinatown, New York, NY 10013",
    "lat": 40.7157, "lng": -73.9978,
    "website": None,
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": None,
    "description": "An intimate Japanese omakase counter in Chinatown earning acclaim for its austere, meditative approach to sushi and kaiseki preparation.",
    "popular_dishes": ["Seasonal omakase sushi"],
    "price_per_item": "$250+ per person",
  },
  "kopitiam-chinatown": {
    "address": "151 East Broadway, New York, NY 10002",
    "lat": 40.7139, "lng": -73.9941,
    "website": "https://kopitiamny.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "NYC's best Malaysian coffee shop — Kyo Pang's Chinatown spot serves the hawker-stall classics of Kuala Lumpur in a cheerful, tile-lined room.",
    "popular_dishes": ["Nasi Lemak", "Kaya Toast", "Curry Laksa", "Half-boiled Eggs"],
    "price_per_item": "$12-22",
  },
  "laghman-express-bensonhurst": {
    "address": "Bensonhurst, Brooklyn, NY 11214",
    "lat": 40.6030, "lng": -73.9983,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Uyghur restaurant in Bensonhurst serving hand-pulled laghman noodles and the bold, cumin-spiced cooking of Central Asia.",
    "popular_dishes": ["Laghman Noodles", "Samsa", "Polo (Rice Pilaf)", "Lamb Kebabs"],
    "price_per_item": "$12-22",
  },
  "lakruwana-stapleton-heights": {
    "address": "668 Bay Street, Staten Island, NY 10304",
    "lat": 40.6277, "lng": -74.0760,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Sri Lankan restaurant on Staten Island serving the aromatic, coconut-rich cooking of the island — one of the few places in NYC for this underrepresented cuisine.",
    "popular_dishes": ["Kottu Roti", "String Hoppers", "Dhal Curry", "Rice and Curry"],
    "price_per_item": "$15-28",
  },
  "le-coucou-soho": {
    "address": "138 Lafayette Street, New York, NY 10013",
    "lat": 40.7200, "lng": -73.9998,
    "website": "https://lecoucou.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Daniel Rose's soaringly beautiful SoHo French restaurant — one of the most romantic dining rooms in New York, with classical technique and a perfectly curated cheese cart.",
    "popular_dishes": ["Sole Meunière", "Lobster Bisque", "Tête de Veau", "Cheese cart"],
    "price_per_item": "$45-95",
  },
  "le-veau-dor-upper-east-side": {
    "address": "129 East 60th Street, New York, NY 10022",
    "lat": 40.7626, "lng": -73.9677,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A revived Upper East Side French classic — the tiny bistro that's been feeding the neighborhood for decades, now back at its best.",
    "popular_dishes": ["Duck Confit", "Steak au Poivre", "Leek Vinaigrette", "Crêpes Suzette"],
    "price_per_item": "$35-65",
  },
  "levant-astoria": {
    "address": "Astoria, Queens, NY 11103",
    "lat": 40.7712, "lng": -73.9306,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new Astoria restaurant bringing the vibrant flavors of the Levant — mezze, grilled meats, and spiced vegetables — to a Queens neighborhood.",
    "popular_dishes": ["Mezze spread", "Grilled lamb", "Fattoush", "Hummus"],
    "price_per_item": "$22-42",
  },
  "lilia-williamsburg": {
    "address": "567 Union Avenue, Brooklyn, NY 11211",
    "lat": 40.7098, "lng": -73.9558,
    "website": "https://lilianewyork.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Missy Robbins's brilliant Williamsburg pasta shrine — the mafaldini with pink peppercorns is one of the city's greatest dishes.",
    "popular_dishes": ["Mafaldini", "Rigatoni with Lamb", "Agnolotti", "Grilled Fish"],
    "price_per_item": "$28-52",
  },
  "little-myanmar-east-village": {
    "address": "East Village, New York, NY 10009",
    "lat": 40.7265, "lng": -73.9844,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "NYC's leading Burmese restaurant, serving the distinctive fermented tea leaf salads and aromatic curries of Myanmar to an appreciative East Village crowd.",
    "popular_dishes": ["Lahpet Thoke (Tea Leaf Salad)", "Mohinga", "Shan Noodles", "Burmese Curry"],
    "price_per_item": "$14-26",
  },
  "lolas-nomad": {
    "address": "NoMad, New York, NY 10016",
    "lat": 40.7454, "lng": -73.9883,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A new NoMad spot fusing Asian and Southern American flavors in an unexpected and exciting way.",
    "popular_dishes": [],
    "price_per_item": "$25-45",
  },
  "lucia-pizza-sheepshead-bay": {
    "address": "2236 Avenue X, Brooklyn, NY 11235",
    "lat": 40.5968, "lng": -73.9552,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Sheepshead Bay Neapolitan pizza destination drawing pilgrims to Brooklyn's southern tip for impeccably charred, airy pies.",
    "popular_dishes": ["Margherita", "White Pizza", "Burrata Pizza"],
    "price_per_item": "$18-28",
  },
  "mam-lower-east-side": {
    "address": "Lower East Side, New York, NY 10002",
    "lat": 40.7189, "lng": -73.9854,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Vietnamese restaurant on the Lower East Side showcasing the fermented, funky, and complex flavors of Hanoi and the north.",
    "popular_dishes": ["Pho", "Bun Bo Hue", "Vietnamese charcuterie", "Fermented dishes"],
    "price_per_item": "$22-42",
  },
  "okdongsik-koreatown": {
    "address": "Koreatown, New York, NY 10001",
    "lat": 40.7488, "lng": -73.9878,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A new Koreatown arrival elevating Korean comfort food with careful sourcing and technique.",
    "popular_dishes": [],
    "price_per_item": "$22-42",
  },
  "okiboru-lower-east-side": {
    "address": "Lower East Side, New York, NY 10002",
    "lat": 40.7189, "lng": -73.9854,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "NYC's dedicated tsukemen (dipping ramen) shop, where thick noodles are dipped in a rich, concentrated broth — a ramen format rarely seen outside Japan.",
    "popular_dishes": ["Classic Tsukemen", "Spicy Tsukemen", "Chashu Pork", "Seasoned Egg"],
    "price_per_item": "$16-24",
  },
  "old-sport-forest-hills": {
    "address": "Forest Hills, Queens, NY 11375",
    "lat": 40.7206, "lng": -73.8459,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Forest Hills halal Chinese restaurant bringing the bold flavors of northwestern China — cumin lamb, hand-pulled noodles — to a Queens neighborhood.",
    "popular_dishes": ["Cumin Lamb", "Hand-pulled Noodles", "Uyghur-style rice"],
    "price_per_item": "$15-28",
  },
  "rafs-noho": {
    "address": "2 Great Jones Street, New York, NY 10012",
    "lat": 40.7256, "lng": -73.9920,
    "website": "https://rafsnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A romantic French-Italian restaurant in NoHo with candlelit booths, excellent pasta, and the feel of a private Parisian supper club.",
    "popular_dishes": ["Cacio e Pepe", "Agnolotti", "Whole Roasted Chicken", "Tiramisu"],
    "price_per_item": "$28-55",
  },
  "raku-east-village": {
    "address": "520 East 5th Street, New York, NY 10009",
    "lat": 40.7255, "lng": -73.9806,
    "website": "https://rakurestaurant.com",
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Japanese restaurant specializing in udon and various small plates, with a cozy East Village following for its careful, understated cooking.",
    "popular_dishes": ["House Udon", "Grilled Skewers", "Gyoza", "Seasonal specials"],
    "price_per_item": "$18-35",
  },
  "randazzos-clam-bar-sheepshead-bay": {
    "address": "2017 Emmons Avenue, Brooklyn, NY 11235",
    "lat": 40.5869, "lng": -73.9391,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A beloved Sheepshead Bay landmark on the water, serving Italian-American seafood classics in a family atmosphere that feels frozen in the best possible way.",
    "popular_dishes": ["Clam Bar platter", "Calamari", "Pasta with Clams", "Whole Lobster"],
    "price_per_item": "$22-45",
  },
  "s-and-p-lunch-flatiron": {
    "address": "Flatiron, New York, NY 10010",
    "lat": 40.7406, "lng": -73.9900,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A beloved no-frills Flatiron lunch counter serving old-school deli sandwiches and soups to generations of New Yorkers since the 1950s.",
    "popular_dishes": ["Egg Salad Sandwich", "Tuna Melt", "Chicken Soup", "Reuben"],
    "price_per_item": "$12-18",
  },
  "sailor-fort-greene": {
    "address": "Fort Greene, Brooklyn, NY 11217",
    "lat": 40.6889, "lng": -73.9745,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Fort Greene restaurant evoking the cooking of the British Isles and Mediterranean with warm hospitality and natural wine.",
    "popular_dishes": [],
    "price_per_item": "$25-48",
  },
  "salty-lunch-lady-ridgewood": {
    "address": "Ridgewood, Queens, NY 11385",
    "lat": 40.7062, "lng": -73.9091,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Ridgewood sandwich shop earning a cult following for its creative, well-constructed sandwiches in an unpretentious neighborhood setting.",
    "popular_dishes": ["Rotating seasonal sandwiches", "Daily specials"],
    "price_per_item": "$12-18",
  },
  "shawnaes-house-stapleton-heights": {
    "address": "Stapleton Heights, Staten Island, NY 10304",
    "lat": 40.6334, "lng": -74.0819,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Staten Island soul food destination where Shaw-naé's home cooking tradition — fried chicken, collard greens, mac and cheese — draws diners from across the city.",
    "popular_dishes": ["Fried Chicken", "Mac and Cheese", "Collard Greens", "Sweet Potato Pie"],
    "price_per_item": "$16-28",
  },
  "shukette-chelsea": {
    "address": "Chelsea, New York, NY 10011",
    "lat": 40.7433, "lng": -73.9994,
    "website": "https://shukettenyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Chelsea Middle Eastern wine bar from the Shuka team, combining Israeli-inspired mezze, natural wine, and a lively, intimate vibe.",
    "popular_dishes": ["Mezze board", "Lamb flatbread", "Fried Cauliflower", "Hummus"],
    "price_per_item": "$18-35",
  },
  "sofreh-prospect-heights": {
    "address": "75 St. Marks Avenue, Brooklyn, NY 11217",
    "lat": 40.6774, "lng": -73.9717,
    "website": "https://sofrehnyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Nasim Alikhani's elegant Persian restaurant in Prospect Heights — the finest Iranian cooking in New York, with the warmth of a family table.",
    "popular_dishes": ["Ghormeh Sabzi", "Zereshk Polo Mahi", "Kashk Bademjan", "Rice dishes"],
    "price_per_item": "$28-52",
  },
  "superiority-burger-east-village": {
    "address": "430 East 9th Street, New York, NY 10009",
    "lat": 40.7260, "lng": -73.9801,
    "website": "https://superiorityburger.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Brooks Headley's legendary vegetarian burger shop — the impossible-to-categorize East Village spot where the veggie burger is legitimately the best burger in the city.",
    "popular_dishes": ["Superiority Burger", "Sloppy Dave", "Soft Serve", "Lentil soup"],
    "price_per_item": "$8-16",
  },
  "sushi-noz-upper-east-side": {
    "address": "181 East 78th Street, New York, NY 10075",
    "lat": 40.7747, "lng": -73.9574,
    "website": "https://sushinoz.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": None,
    "description": "An intimate Upper East Side omakase counter where chef Nozomu Abe uses aged fish and slow fermentation to create sushi unlike anything else in New York.",
    "popular_dishes": ["Seasonal omakase — aged fish specialty"],
    "price_per_item": "$375+ per person",
  },
  "sushi-ouji-soho": {
    "address": "SoHo, New York, NY 10012",
    "lat": 40.7248, "lng": -74.0019,
    "website": None,
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": None,
    "description": "A SoHo omakase that earns its place at the top of NYC's competitive sushi scene with precision, personality, and exceptional sourcing.",
    "popular_dishes": ["Seasonal omakase sushi"],
    "price_per_item": "$150+ per person",
  },
  "taiwanese-gourmet-elmhurst": {
    "address": "8411 Broadway, Elmhurst, Queens, NY 11373",
    "lat": 40.7371, "lng": -73.8804,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Queens Taiwanese restaurant beloved for its home-style cooking — three-cup chicken, oyster vermicelli, and the kind of food you'd find at a family table in Taipei.",
    "popular_dishes": ["Three-Cup Chicken", "Oyster Vermicelli", "Braised Pork Rice", "Scallion Pancake"],
    "price_per_item": "$12-22",
  },
  "temple-canteen-flushing": {
    "address": "Flushing, Queens, NY 11355",
    "lat": 40.7580, "lng": -73.8303,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Flushing Indian spot serving the vegetarian cooking associated with temple kitchens — pure, aromatic, and deeply satisfying.",
    "popular_dishes": ["Thali", "Sambar", "Dosa", "Temple-style sweets"],
    "price_per_item": "$12-22",
  },
  "thai-diner-nolita": {
    "address": "186 Mott Street, New York, NY 10012",
    "lat": 40.7218, "lng": -73.9956,
    "website": "https://thaidiner.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Ann Redding and Matt Danzer's Thai diner on Mott Street — the creative successors to Uncle Boons, blending American diner comfort with bold Thai flavor.",
    "popular_dishes": ["Pad Thai Pancake", "Thai Iced Tea Soft Serve", "Crying Tiger Steak", "Larb Fried Chicken"],
    "price_per_item": "$18-35",
  },
  "third-falcon-fort-greene": {
    "address": "Fort Greene, Brooklyn, NY 11217",
    "lat": 40.6889, "lng": -73.9745,
    "website": None,
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Fort Greene restaurant marrying French bistro precision with American hospitality in a warmly lit neighborhood room.",
    "popular_dishes": ["Steak Frites", "Roast Chicken", "Seasonal vegetables"],
    "price_per_item": "$25-48",
  },
  "torrisi-nolita": {
    "address": "275 Mulberry Street, New York, NY 10012",
    "lat": 40.7229, "lng": -73.9961,
    "website": "https://torrisinyc.com",
    "walk_in_friendly": False, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Rich Torrisi's flagship return — an Italian-American restaurant that treats the canon with deep respect and brilliant technique in a buzzy NoLIta room.",
    "popular_dishes": ["Lobster Fra Diavolo", "Clam Pizza", "Antipasto", "House-made Pasta"],
    "price_per_item": "$35-75",
  },
  "trinciti-roti-shop-south-ozone-park": {
    "address": "South Ozone Park, Queens, NY 11420",
    "lat": 40.6697, "lng": -73.8243,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A Queens Trinidadian roti shop beloved by the South Asian Caribbean community — buss-up-shut, doubles, and curried meats wrapped in flaky paratha.",
    "popular_dishes": ["Buss-Up-Shut Roti", "Chicken Curry Roti", "Doubles", "Goat Curry"],
    "price_per_item": "$8-18",
  },
  "txikito-chelsea": {
    "address": "240 Ninth Avenue, New York, NY 10001",
    "lat": 40.7478, "lng": -73.9991,
    "website": "https://txikitonyc.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Alex Raij's Chelsea Basque restaurant — pintxos, salt cod, and cider in a warm, idiosyncratic room that feels transported from San Sebastián.",
    "popular_dishes": ["Salt Cod Fritters", "Pintxos", "Basque Cheesecake", "Txistorra"],
    "price_per_item": "$18-38",
  },
  "una-pizza-napoletana-lower-east-side": {
    "address": "175 Orchard Street, New York, NY 10002",
    "lat": 40.7199, "lng": -73.9884,
    "website": "https://unapizza.com",
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Anthony Mangieri's legendary Neapolitan pizza shop — only a handful of pies served, only on certain days, but they may be the finest pizza in New York.",
    "popular_dishes": ["Margherita", "Filetti", "Bianca", "Ilaria"],
    "price_per_item": "$22-30",
  },
  "via-carota-west-village": {
    "address": "51 Grove Street, New York, NY 10014",
    "lat": 40.7333, "lng": -74.0019,
    "website": "https://viacarota.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "Jody Williams and Rita Sodi's beloved West Village Italian trattoria — the insalata verde is perfect, the pasta is better, and the room is always packed.",
    "popular_dishes": ["Insalata Verde", "Cacio e Pepe", "Roast Chicken", "Crostini"],
    "price_per_item": "$22-42",
  },
  "village-cafe-gravesend": {
    "address": "Gravesend, Brooklyn, NY 11223",
    "lat": 40.5974, "lng": -73.9636,
    "website": None,
    "walk_in_friendly": None, "reservation_required": None, "reservation_platform": None,
    "description": "A Brooklyn Azerbaijani restaurant serving the hearty, aromatic cooking of the South Caucasus — dolma, kebabs, and fragrant rice dishes.",
    "popular_dishes": ["Dolma", "Lamb Kebab", "Plov", "Dushbara soup"],
    "price_per_item": "$18-35",
  },
  "white-bear-flushing": {
    "address": "135-02 Roosevelt Avenue, Flushing, Queens, NY 11354",
    "lat": 40.7536, "lng": -73.8300,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "A tiny Flushing counter famous for wontons — spicy, hand-folded, and served in a chile oil so good people order extra just to drink it.",
    "popular_dishes": ["Spicy Wontons (#6)", "Pork Dumplings", "Shrimp Wontons"],
    "price_per_item": "$5-12",
  },
  "yoon-haeundae-galbi-koreatown": {
    "address": "12 West 32nd Street, New York, NY 10001",
    "lat": 40.7486, "lng": -73.9880,
    "website": "https://yoonhaeundaegalbi.com",
    "walk_in_friendly": None, "reservation_required": True, "reservation_platform": "Resy",
    "description": "A Koreatown Korean BBQ specialist focused on Haeundae-style galbi — premium short ribs marinated and grilled tableside in an upscale but lively room.",
    "popular_dishes": ["Galbi (Short Rib)", "Bulgogi", "Samgyeopsal", "Pajeon"],
    "price_per_item": "$45-95",
  },
  "zaab-zaab-elmhurst": {
    "address": "76-04 Woodside Avenue, Elmhurst, Queens, NY 11373",
    "lat": 40.7371, "lng": -73.8804,
    "website": None,
    "walk_in_friendly": True, "reservation_required": False, "reservation_platform": None,
    "description": "Queens' essential Isaan Thai restaurant — funky, fermented, fiercely spiced northeastern Thai cooking from a family kitchen with no interest in softening anything.",
    "popular_dishes": ["Larb", "Nam Tok", "Papaya Salad", "Isaan Sausage"],
    "price_per_item": "$12-22",
  },
}

def merge():
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    patched = 0
    for restaurant in data:
        rid = restaurant["id"]
        if rid in PATCHES:
            for key, val in PATCHES[rid].items():
                # Only overwrite if the base value is empty/null
                if restaurant.get(key) in (None, "", [], False) or key in (
                    "description", "popular_dishes", "address", "lat", "lng",
                    "website", "price_per_item", "walk_in_friendly",
                    "reservation_required", "reservation_platform"
                ):
                    restaurant[key] = val
            patched += 1
    DATA_FILE.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    print(f"Patched {patched} restaurants.")

if __name__ == "__main__":
    merge()
